// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VIMC_SRAM__SYMS_H_
#define VERILATED_VIMC_SRAM__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vimc_sram.h"

// INCLUDE MODULE CLASSES
#include "Vimc_sram___024root.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)Vimc_sram__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vimc_sram* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vimc_sram___024root            TOP;

    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_imc_sram;
    VerilatedScope __Vscope_imc_sram__accum;
    VerilatedScope __Vscope_imc_sram__col_dec;
    VerilatedScope __Vscope_imc_sram__compute;
    VerilatedScope __Vscope_imc_sram__fsm;
    VerilatedScope __Vscope_imc_sram__row_dec_read;
    VerilatedScope __Vscope_imc_sram__row_dec_write;
    VerilatedScope __Vscope_imc_sram__sram;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__0__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__10__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__11__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__12__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__13__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__14__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__15__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__1__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__2__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__3__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__4__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__5__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__6__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__7__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__8__KET____col_gen__BRA__9__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__0__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__10__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__11__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__12__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__13__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__14__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__15__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__1__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__2__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__3__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__4__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__5__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__6__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__7__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__8__KET____bit_cell;
    VerilatedScope __Vscope_imc_sram__sram__row_gen__BRA__9__KET____col_gen__BRA__9__KET____bit_cell;

    // CONSTRUCTORS
    Vimc_sram__Syms(VerilatedContext* contextp, const char* namep, Vimc_sram* modelp);
    ~Vimc_sram__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
